### ISSUE TITLE
I cant seem to set a master password and now it wont let me in to Tor

### ISSUE THREAD

**Issue by mcdnben** [vanowm/MasterPasswordPlus#125] opened 2017-07-19 20:07 UTC
Hey,

This keeps coming up with 'unable to change master password' but I appear to be logged out

**Comment by mcdnben** [comment] 2017-07-19 20:08
*locked out

**Comment by vanowm** [comment] 2017-07-19 21:17
Duplicate of #120 
Hopefully will have some free time in next 2 weeks to fix this.

**Closed by vanowm** 2017-07-19 21:17 UTC
Labels: bug
