### ISSUE TITLE
Unable to set master Password

### ISSUE THREAD

**Issue by mindovermiles262** [vanowm/MasterPasswordPlus#126] opened 2017-07-26 19:08 UTC
System Information
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```
Firefox 54.0 (64-bit)

When trying to set the initial MP+ master password I am able to enter it in the fields, but the 'ok' button does not submit.  The 'cancel' button works to clear.

![screenshot_2017-07-26_12-03-19](https://user-images.githubusercontent.com/14863257/28638968-66d56dc8-71fb-11e7-9f11-9eaec3343fc2.png)

**Comment by vanowm** [comment] 2017-07-30 09:09
Duplicate of #120

**Closed by vanowm** 2017-07-30 09:09 UTC
