### ISSUE TITLE
Password required form not fully appear

### ISSUE THREAD

**Issue by r-zal** [vanowm/MasterPasswordPlus#104] opened 2016-11-18 03:16 UTC
![screenshot_1](https://cloud.githubusercontent.com/assets/17342062/20417462/05405c6e-ad78-11e6-88c5-ac8b06d8b0a8.png)

this happen on mozilla firefox 50

**Comment by vanowm** [comment] 2016-11-18 03:27
Duplicate of #102

**Closed by vanowm** 2016-11-18 03:27 UTC
